"use client";
import {useEffect,useRef,useState} from "react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Progress} from "@/components/ui/progress";
import {Crosshair,Lock,RotateCcw,Square,Volume2,VolumeX} from "lucide-react";

type Kind="hyp"|"legX"|"legY"|"angle"|"lead"|"arc";
type Task={kind:Kind,x:number,y:number,dec:number,label:string,speed?:number,flight?:number};
type Stage={name:string,short:string,brief:string,tasks:Task[]};
type Shot={hit:boolean,ratio:number,path:string,endX:number,endY:number};
const stages:Stage[]=[
 {name:"ILMALAIVAT LAAKSOSSA",short:"KENTTÄ 1",brief:"Torju laaksoa lähestyvät ilmalaivat.",tasks:[{kind:"hyp",x:3,y:4,dec:1,label:""},{kind:"hyp",x:6,y:8,dec:1,label:""},{kind:"hyp",x:5,y:7,dec:1,label:""},{kind:"hyp",x:11,y:8,dec:1,label:""}]},
 {name:"KAKSITASOJEN HYÖKKÄYS",short:"KENTTÄ 2",brief:"Pysäytä laaksoon laskeutuvat kaksitasot.",tasks:[{kind:"legX",x:6,y:8,dec:1,label:""},{kind:"legY",x:12,y:5,dec:1,label:""},{kind:"legX",x:7,y:6,dec:1,label:""},{kind:"legY",x:10,y:7,dec:1,label:""}]}
];
const taskPools:Task[][]=[
 [{kind:"hyp",x:3,y:4,dec:1,label:""},{kind:"hyp",x:6,y:8,dec:1,label:""},{kind:"hyp",x:5,y:7,dec:1,label:""},{kind:"hyp",x:11,y:8,dec:1,label:""},{kind:"hyp",x:4,y:7,dec:1,label:""},{kind:"hyp",x:8,y:9,dec:1,label:""},{kind:"hyp",x:9,y:6,dec:1,label:""},{kind:"hyp",x:10,y:7,dec:1,label:""},{kind:"hyp",x:7,y:9,dec:1,label:""},{kind:"hyp",x:12,y:5,dec:1,label:""},{kind:"hyp",x:8,y:4,dec:1,label:""},{kind:"hyp",x:3,y:8,dec:1,label:""}],
 [{kind:"legX",x:6,y:8,dec:1,label:""},{kind:"legY",x:12,y:5,dec:1,label:""},{kind:"legX",x:7,y:6,dec:1,label:""},{kind:"legY",x:10,y:7,dec:1,label:""},{kind:"legX",x:9,y:4,dec:1,label:""},{kind:"legY",x:8,y:6,dec:1,label:""},{kind:"legX",x:11,y:7,dec:1,label:""},{kind:"legY",x:5,y:9,dec:1,label:""},{kind:"legX",x:4,y:8,dec:1,label:""},{kind:"legY",x:7,y:5,dec:1,label:""},{kind:"legX",x:10,y:6,dec:1,label:""},{kind:"legY",x:9,y:8,dec:1,label:""}]
];
const randomTasks=(n:number)=>[...taskPools[n]].sort(()=>Math.random()-.5).slice(0,8);
const total=16;
const value=(t:Task)=>t.kind==="hyp"?Math.hypot(t.x,t.y):t.kind==="legX"?t.x:t.kind==="legY"?t.y:t.kind==="angle"?Math.atan2(t.y,t.x)*180/Math.PI:t.kind==="lead"?t.x-(t.speed||0)*(t.flight||0):-.1*t.x*t.x+1.8*t.x;
const taskLimit=(stage:number,step:number)=>Math.max(30,90-4*(stage*8+step));
const stageLives=[3,3,3,2,2];
const hints=["Pythagoras","Pythagoras","Trigonometria","Tasainen liike","Sijoita x"];
function boom(c:AudioContext,stage:number){const profiles=[[58,.32,.92],[72,.22,.72],[66,.14,.82],[105,.055,.34],[145,.48,1.3]][stage];const shots=stage===3?8:stage===4?1:4;for(let i=0;i<shots;i++){const delay=i*profiles[1],o=c.createOscillator(),g=c.createGain();o.type=stage===4?"sine":"sawtooth";o.frequency.setValueAtTime(profiles[0]+i*2,c.currentTime+delay);if(stage===4)o.frequency.exponentialRampToValueAtTime(420,c.currentTime+delay+profiles[2]);g.gain.setValueAtTime(.001,c.currentTime+delay);g.gain.linearRampToValueAtTime(stage===3?.055:.09,c.currentTime+delay+.018);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+delay+profiles[2]);o.connect(g).connect(c.destination);o.start(c.currentTime+delay);o.stop(c.currentTime+delay+profiles[2])}}
function engine(c:AudioContext,stage:number){const base=[38,78,54,42,125][stage],pulses=[2,4,3,6,1][stage];for(let i=0;i<pulses;i++){const o=c.createOscillator(),g=c.createGain(),d=i*(stage===3?.13:.18);o.type=stage===4?"sine":"triangle";o.frequency.value=base+(i%2)*7;g.gain.setValueAtTime(.001,c.currentTime+d);g.gain.linearRampToValueAtTime(stage===3?.018:.009,c.currentTime+d+.02);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+d+.24);o.connect(g).connect(c.destination);o.start(c.currentTime+d);o.stop(c.currentTime+d+.25)}}

export default function Home(){
 const [started,setStarted]=useState(false),[stage,setStage]=useState(0),[step,setStep]=useState(0),[lives,setLives]=useState(3),[answer,setAnswer]=useState(""),[message,setMessage]=useState("VALMIINA"),[shot,setShot]=useState<Shot|null>(null),[sound,setSound]=useState(true),[done,setDone]=useState(false),[briefing,setBriefing]=useState(false),[firing,setFiring]=useState(false),[bombing,setBombing]=useState(false),[danger,setDanger]=useState(false),[time,setTime]=useState(taskLimit(0,0)),[unlocked,setUnlocked]=useState(0),[runStages,setRunStages]=useState<Stage[]>(stages);
 const audio=useRef<AudioContext|null>(null),music=useRef<HTMLAudioElement|null>(null),ambient=useRef<HTMLAudioElement|null>(null),activeSounds=useRef<HTMLAudioElement[]>([]),timers=useRef<number[]>([]);const s=runStages[stage],t=s.tasks[step],prior=runStages.slice(0,stage).reduce((n,v)=>n+v.tasks.length,0),maxLives=stageLives[stage],threat=maxLives-lives,currentX=Math.max(1,t.x-threat),currentY=Math.max(1,t.y-(stage===1?threat*.5:0)),correct=t.kind==="hyp"?Math.hypot(currentX,currentY):t.kind==="legX"?currentX:currentY,slant=Math.hypot(currentX,currentY),tx=currentX/12*100,ty=currentY/10*100;
 const context=()=>audio.current||(audio.current=new AudioContext());
 const musicOn=()=>{if(!music.current){music.current=new Audio("/assets/audio/harmaan-kentan-kaiut.mp3");music.current.loop=true;music.current.volume=.22}music.current.play().catch(()=>{})};
 const play=(src:string,volume=1)=>{if(!sound)return;const a=new Audio(src);a.volume=volume;activeSounds.current.push(a);a.onended=()=>{activeSounds.current=activeSounds.current.filter(v=>v!==a)};a.play().catch(()=>{});return a};
 const afterAudio=(src:string,volume:number,callback:()=>void,gap=220)=>{const a=play(src,volume);if(!a){timers.current.push(window.setTimeout(callback,300));return}let finished=false;const finish=()=>{if(finished)return;finished=true;timers.current.push(window.setTimeout(callback,gap))};a.addEventListener("ended",finish,{once:true});a.addEventListener("error",finish,{once:true});timers.current.push(window.setTimeout(finish,8000))};
 const playSequence=(clips:{src:string,volume:number}[],done:()=>void)=>{const next=(i:number)=>i>=clips.length?done():afterAudio(clips[i].src,clips[i].volume,()=>next(i+1),320);next(0)};
 const stopSounds=()=>{ambient.current?.pause();ambient.current=null;activeSounds.current.forEach(a=>{a.pause();a.currentTime=0});activeSounds.current=[]};
 const startAmbient=(n:number)=>{ambient.current?.pause();if(!sound||!started||done)return;const a=new Audio(`/assets/audio/engines/${n===0?"zeppelin":"biplane"}.mp3`);a.loop=true;a.volume=n===0?.16:.22;ambient.current=a;a.play().catch(()=>{})};
 const taskVoice=(task:Task)=>task.kind==="hyp"?"calculate-direct":task.kind==="legX"?"calculate-horizontal":"check-altitude-distance";
 const clear=()=>{timers.current.forEach(clearTimeout);timers.current=[]};useEffect(()=>()=>clear(),[]);
 useEffect(()=>{if(started&&sound&&!done)startAmbient(stage);else{ambient.current?.pause();ambient.current=null}return()=>{ambient.current?.pause()}},[started,sound,done,stage]);
 useEffect(()=>{if(!started||briefing||firing||bombing||shot||done||time<=0)return;const id=window.setInterval(()=>setTime(v=>Math.max(0,v-1)),1000);return()=>clearInterval(id)},[started,briefing,firing,bombing,shot,done,time]);
 useEffect(()=>{if(time!==0||briefing||firing||bombing||shot||done)return;setDanger(true);setMessage("AIKA LOPPUI — KOHDE LÄHESTYY");afterAudio("/assets/audio/voice/too-late.mp3",.9,()=>{if(lives===1){setBombing(true);timers.current.push(window.setTimeout(()=>{setMessage("POMMIT IRTI — SUOJAAN");play("/assets/audio/effects/bomb-whistle.mp3",.48)},1700),window.setTimeout(()=>advance(false),5000))}else advance(false)},900)},[time,briefing,firing,bombing,shot,done,lives]);
 function startAt(n:number){clear();stopSounds();if(sound)musicOn();const nextTasks=randomTasks(n);setRunStages(v=>v.map((item,i)=>i===n?{...item,tasks:nextTasks}:item));setStage(n);setStep(0);setLives(stageLives[n]);setTime(taskLimit(n,0));setAnswer("");setMessage("KUUNTELE KOMENTAJAA");setShot(null);setDone(false);setFiring(false);setBombing(false);setDanger(false);setBriefing(true);setStarted(true);const clips=n===0?[{src:"/assets/audio/voice/nation-danger.mp3",volume:.92},{src:"/assets/audio/voice/intro-1.mp3",volume:.92},{src:`/assets/audio/voice/${taskVoice(nextTasks[0])}.mp3`,volume:.88},{src:"/assets/audio/voice/precision.mp3",volume:.84}]:[{src:"/assets/audio/voice/intro-2.mp3",volume:.92},{src:`/assets/audio/voice/${taskVoice(nextTasks[0])}.mp3`,volume:.88},{src:"/assets/audio/voice/precision.mp3",volume:.84}];timers.current.push(window.setTimeout(()=>playSequence(clips,()=>{setBriefing(false);setMessage("LASKE AMPUMA-ARVO")}),350))}
 function reset(){startAt(0)}
 function stop(){clear();stopSounds();audio.current?.suspend();if(music.current){music.current.pause();music.current.currentTime=0}setStarted(false);setShot(null)}
 function toggleSound(){if(sound){stopSounds();audio.current?.suspend();music.current?.pause();setSound(false)}else{context().resume();musicOn();setSound(true)}}
 function advance(hit:boolean){setShot(null);setAnswer("");setFiring(false);setDanger(false);if(!hit){const n=lives-1;setLives(n);if(!n){setDone(true);setBombing(false);setMessage("PATTERI MENETETTY");play("/assets/audio/effects/ground-explosion.mp3",.72);timers.current.push(window.setTimeout(()=>play("/assets/audio/voice/battery-hit.mp3",.92),650),window.setTimeout(()=>play("/assets/audio/voice/position-lost.mp3",.9),4400))}else{setBombing(false);setTime(taskLimit(stage,step));setMessage("KOHDE LÄHESTYY — LASKE UUDELLEEN");play("/assets/audio/voice/target-closing.mp3",.88)}return}if(step<s.tasks.length-1){const nextStep=step+1,next=s.tasks[nextStep];setStep(nextStep);setTime(taskLimit(stage,nextStep));setMessage("UUSI TUTKAKONTAKTI");timers.current.push(window.setTimeout(()=>play(`/assets/audio/voice/${taskVoice(next)}.mp3`,.84),900))}else if(stage<stages.length-1){setUnlocked(1);setMessage("KENTTÄ 1 TORJUTTU — VALMISTAUDU SEURAAVAAN");timers.current.push(window.setTimeout(()=>startAt(stage+1),1600))}else{setDone(true);setMessage("KAIKKI 16 HYÖKKÄYSTÄ TORJUTTU");play("/assets/audio/voice/victory.mp3",.92)}}
 function fire(){if(briefing||firing||bombing||shot||done)return;const v=Number(answer.replace(",","."));if(!Number.isFinite(v)){setMessage("ANNA LUKU");return}const hit=Math.abs(v-correct)<.051,ratio=Math.max(.25,Math.min(1.45,v/correct)),ex=tx*ratio,ey=ty*ratio,apex=ey+4,nextShot={hit,ratio,path:`M 0 91 Q ${ex*.48} ${100-apex} ${ex} ${100-ey}`,endX:ex,endY:ey};setFiring(true);setMessage("ODOTA TULIKOMENTOA");afterAudio("/assets/audio/voice/fire.mp3",.95,()=>{setFiring(false);setDanger(!hit);setShot(nextShot);setMessage("YHTEISLAUKAUS — SEURAA RATAA");play(`/assets/audio/effects/cannon-${stage+1}.mp3`,.72);timers.current.push(window.setTimeout(()=>{setMessage(hit?"OSUMA — AMPUMA-ARVO OIKEA":ratio<1?"LAUKAUS JÄI LYHYEKSI":"LAUKAUS MENI OHI");play("/assets/audio/effects/flak.mp3",.58);if(!hit&&lives===1){setMessage("TORJUNTA EPÄONNISTUI — KOHDE YLITTÄÄ PATTERIN");setBombing(true);timers.current.push(window.setTimeout(()=>{setMessage("POMMIT IRTI — SUOJAAN");play("/assets/audio/effects/bomb-whistle.mp3",.48)},1700),window.setTimeout(()=>advance(false),5000))}else timers.current.push(window.setTimeout(()=>afterAudio(`/assets/audio/voice/${hit?"hit":"miss"}.mp3`,.9,()=>advance(hit),hit?850:1100),650))},3900))},120)}
 if(!started)return <main className="intro"><section><small>MATEMAATTINEN TOIMINTAPELI · PYTHAGORAAN LAUSE</small><h1>PYTHAGORAAN<br/>TORJUNTAJOUKOT</h1><p>Johda torjuntajoukkoja, tulkitse koordinaatistoa ja laske oikeat ampuma-arvot. Toinen kenttä avautuu ensimmäisen kentän läpäisemisen jälkeen.</p><div className="intro-rule"><span>2 KENTTÄÄ</span><span>16 TEHTÄVÄÄ</span><span>90–30 SEKUNTIA</span></div><div className="stage-list">{stages.map((v,i)=>{const locked=i>unlocked;return <button key={v.name} className={locked?"locked":""} disabled={locked} onClick={()=>startAt(i)}><b>0{i+1}</b><span>{v.name}</span><em>{locked?<><Lock/> LUKITTU</>:"ALOITA KENTTÄ"}</em></button>})}</div><Button className="primary-start" onClick={reset}>ALOITA ENSIMMÄISESTÄ KENTÄSTÄ</Button></section></main>;
 const answerLabel=t.kind==="angle"?"SUUNTAKULMA (°)":t.kind==="lead"?"TULEVA VAAKAETÄISYYS (km)":t.kind==="arc"?"RADAN KORKEUS (km)":t.kind==="legX"?"VAAKAETÄISYYS (km)":t.kind==="legY"?"KORKEUS (km)":"SUORA ETÄISYYS (km)";
 const fmt=(n:number)=>n.toFixed(1).replace(".",",");
 const fmt2=(n:number)=>n.toFixed(2).replace(".",",");
 const taskText=t.kind==="hyp"?`Kohde lentää ${fmt(currentY)} km:n korkeudessa ja sen vaakaetäisyys patterista on ${fmt(currentX)} km. Laske patterin ja kohteen välinen suora etäisyys.`:t.kind==="legX"?`Kohteen suora etäisyys patterista on ${fmt2(slant)} km ja lentokorkeus ${fmt(currentY)} km. Laske kohteen vaakaetäisyys.`:`Kohteen suora etäisyys patterista on ${fmt2(slant)} km ja vaakaetäisyys ${fmt(currentX)} km. Laske kohteen lentokorkeus.`;
 return <main className={`game era-${stage} threat-${threat} ${danger?"danger":""} ${done&&!lives?"lost":""}`}><header><div><small>KENTTÄ {stage+1}/2</small><strong>{s.name}</strong></div><nav className="field-switch" aria-label="Vaihda kenttää">{stages.map((v,i)=><button key={v.name} disabled={i>unlocked} className={i===stage?"active":""} onClick={()=>startAt(i)} aria-label={`Kenttä ${i+1}: ${v.name}`}>{i>unlocked?<Lock/>:i+1}</button>)}</nav><div className="actions"><span className="counter">{prior+step+1}<i> / {total}</i></span><button onClick={toggleSound} aria-label={sound?"Mykistä äänet":"Ota äänet käyttöön"}>{sound?<Volume2/>:<VolumeX/>}<span>{sound?"ÄÄNET":"MYKISTETTY"}</span></button><button onClick={stop}><Square/> <span>LOPETA</span></button></div></header>
 <section className="combat-row"><section className="field"><div className="alarm"/><div className="beam one"/><div className="beam two"/><div className="grid"><span className="origin">(0, 0)</span><span className="xlab">12 km</span><span className="ylab">10 km</span><div className="triangle" style={{width:`${tx}%`,height:`${ty}%`}}><i className="horizontal"/><i className="vertical"/><i className="direct" style={{transform:`rotate(${-Math.atan2(ty,tx)*180/Math.PI}deg)`}}/></div><div className={`formation craft-${stage} ${shot?.hit?"hit":""} ${bombing||done&&!lives?"overrun":""}`} style={{left:`${tx}%`,bottom:`${ty}%`}}>{Array.from({length:2},(_,i)=><img key={i} className={`p${i+1}`} src={`/assets/targets/target-${stage+1}.png`} alt={i?"":stage===0?"Lähestyvät ilmalaivat":"Lähestyvät kaksitasot"}/>)}</div>{bombing&&<div className="falling-bombs" style={{left:`${Math.max(18,tx*.48)}%`,bottom:`${Math.max(28,ty*.72)}%`}}><i/><i/></div>}<div className={`battery weapon-${stage} ${done&&!lives?"destroyed":""}`}>{Array.from({length:2},(_,i)=><img key={i} className={shot?"recoil":""} src={`/assets/weapons/weapon-${stage+1}.png`} alt={i?"":"Torjuntapatteri"}/>)}</div>{shot&&<svg className="trajectory" viewBox="0 0 100 100" preserveAspectRatio="none">{[0,1].map(i=><path key={i} d={shot.path} className={`trail trail-${i}`}/>)}<circle className="projectile" r={.7}><animateMotion dur="3.8s" path={shot.path} fill="freeze"/></circle></svg>}{shot&&<div className={`burst ${shot.hit?"good":"bad"}`} style={{left:`${shot.endX}%`,bottom:`${shot.endY}%`}}/>}{done&&!lives&&<div className="ground-blasts"><i/><i/><i/></div>}</div></section>
 <aside className={`task-panel ${briefing?"is-briefing":""}`}>{briefing?<div className="briefing-card"><small>KOMENTAJAN TILANNEKATSAUS</small><h2>Kuuntele tehtävänanto.</h2><i/><p>Tehtäväarvot avautuvat puheen jälkeen.</p></div>:<><div className="task-meta"><small>TEHTÄVÄ {step+1}/{s.tasks.length}</small><div className={`panel-timer ${time<=10?"urgent":""}`}><span>AIKAA</span><b>{time} s</b></div></div><Progress className="panel-timebar" value={time/taskLimit(stage,step)*100}/><h2>{taskText}</h2><p className="precision">Anna vastaus yhden desimaalin tarkkuudella.</p><div className="measurements">{t.kind!=="legX"&&<span><small>VAAKAETÄISYYS</small>{fmt(currentX)} km</span>}{t.kind!=="legY"&&<span><small>KORKEUS</small>{fmt(currentY)} km</span>}{t.kind!=="hyp"&&<span><small>SUORA ETÄISYYS</small>{fmt2(slant)} km</span>}</div>{lives<maxLives&&<em>VIHJE: {hints[stage]}</em>}<div className="entry">{done?<Button onClick={reset}><RotateCcw/> ALOITA ALUSTA</Button>:<><label>{answerLabel}</label><div><Input value={answer} inputMode="decimal" disabled={firing||bombing||!!shot||time<=0} onChange={e=>setAnswer(e.target.value)} onKeyDown={e=>e.key==="Enter"&&fire()}/><Button onClick={fire} disabled={firing||bombing||!!shot||time<=0}><Crosshair/> TULTA</Button></div></>}</div></>}</aside></section>
 <section className="console"><div className="mission"><small>{s.short}</small><strong>{message}</strong><Progress value={(prior+step)/total*100}/></div><div className="lives"><small>SALLITUT HUDIT</small><div>{Array.from({length:maxLives-1},(_,i)=><i key={i} className={i<Math.max(0,lives-1)?"on":""}/>)}</div></div></section></main>
}
